name: base
channels:
  - plotly
  - conda-forge
  - defaults
dependencies:
  - anyio=3.6.2
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - arrow-cpp=12.0.0
  - asttokens=2.2.1
  - attrs=23.1.0
  - aws-c-auth=0.6.27
  - aws-c-cal=0.5.26
  - aws-c-common=0.8.19
  - aws-c-compression=0.2.16
  - aws-c-event-stream=0.2.20
  - aws-c-http=0.7.7
  - aws-c-io=0.13.21
  - aws-c-mqtt=0.8.11
  - aws-c-s3=0.3.0
  - aws-c-sdkutils=0.1.9
  - aws-checksums=0.1.14
  - aws-crt-cpp=0.20.1
  - aws-sdk-cpp=1.10.57
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - beautifulsoup4=4.12.2
  - bleach=6.0.0
  - blosc=1.21.4
  - bokeh=3.1.1
  - boltons=23.0.0
  - boost-cpp=1.78.0
  - branca=0.6.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.19.0
  - ca-certificates=2023.5.7
  - cairo=1.16.0
  - certifi=2023.5.7
  - cffi=1.15.1
  - cfitsio=4.2.0
  - charset-normalizer=3.1.0
  - click=8.1.3
  - click-plugins=1.1.1
  - cligj=0.7.2
  - cloudpickle=2.2.1
  - colorama=0.4.6
  - comm=0.1.3
  - conda=23.3.1
  - conda-content-trust=0.1.3
  - conda-package-handling=2.0.2
  - conda-package-streaming=0.7.0
  - contourpy=1.0.7
  - cryptography=40.0.2
  - curl=8.1.0
  - cycler=0.11.0
  - cytoolz=0.12.0
  - dask=2023.5.0
  - dask-core=2023.5.0
  - debugpy=1.6.7
  - decorator=5.1.1
  - defusedxml=0.7.1
  - distributed=2023.5.0
  - entrypoints=0.4
  - executing=1.2.0
  - expat=2.5.0
  - fiona=1.9.4
  - flit-core=3.9.0
  - folium=0.14.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.39.4
  - freetype=2.12.1
  - freexl=1.0.6
  - fsspec=2023.5.0
  - gdal=3.7.0
  - geopandas=0.13.0
  - geopandas-base=0.13.0
  - geos=3.11.2
  - geotiff=1.7.1
  - gettext=0.21.1
  - gflags=2.2.2
  - glog=0.6.0
  - h3-py=3.7.6
  - hdf4=4.2.15
  - hdf5=1.14.0
  - icu=72.1
  - idna=3.4
  - importlib-metadata=6.6.0
  - importlib_metadata=6.6.0
  - importlib_resources=5.12.0
  - intel-openmp=2023.1.0
  - ipykernel=6.23.1
  - ipython=8.13.2
  - ipython_genutils=0.2.0
  - jedi=0.18.2
  - jinja2=3.1.2
  - joblib=1.2.0
  - jsonpatch=1.32
  - jsonpointer=2.0
  - jsonschema=4.17.3
  - jupyter_client=8.2.0
  - jupyter_core=5.3.0
  - jupyter_events=0.6.3
  - jupyter_server=2.5.0
  - jupyter_server_terminals=0.4.4
  - jupyterlab_pygments=0.2.2
  - kealib=1.5.1
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lcms2=2.15
  - lerc=4.0.0
  - libabseil=20230125.0
  - libaec=1.0.6
  - libarchive=3.6.2
  - libarrow=12.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libcrc32c=1.1.2
  - libcurl=8.1.0
  - libdeflate=1.18
  - libevent=2.1.12
  - libexpat=2.5.0
  - libffi=3.4.2
  - libgdal=3.7.0
  - libglib=2.76.2
  - libgoogle-cloud=2.10.0
  - libgrpc=1.54.2
  - libhwloc=2.9.1
  - libiconv=1.17
  - libjpeg-turbo=2.1.5.1
  - libkml=1.3.0
  - liblapack=3.9.0
  - libnetcdf=4.9.2
  - libpng=1.6.39
  - libpq=15.3
  - libprotobuf=3.21.12
  - librttopo=1.1.0
  - libsodium=1.0.18
  - libspatialindex=1.9.3
  - libspatialite=5.0.1
  - libsqlite=3.42.0
  - libssh2=1.10.0
  - libthrift=0.18.1
  - libtiff=4.5.0
  - libutf8proc=2.8.0
  - libwebp-base=1.3.0
  - libxcb=1.15
  - libxml2=2.10.4
  - libzip=1.9.2
  - libzlib=1.2.13
  - locket=1.0.0
  - lz4=4.3.2
  - lz4-c=1.9.4
  - lzo=2.10
  - mapclassify=2.5.0
  - markupsafe=2.1.2
  - matplotlib-base=3.7.1
  - matplotlib-inline=0.1.6
  - mistune=2.0.5
  - mkl=2023.1.0
  - msgpack-python=1.0.5
  - munch=3.0.0
  - munkres=1.1.4
  - nbclassic=1.0.0
  - nbclient=0.7.4
  - nbconvert=7.4.0
  - nbconvert-core=7.4.0
  - nbconvert-pandoc=7.4.0
  - nbformat=5.8.0
  - nest-asyncio=1.5.6
  - networkx=3.1
  - notebook=6.5.4
  - notebook-shim=0.2.3
  - numpy=1.24.3
  - openjpeg=2.5.0
  - openssl=3.1.0
  - orc=1.8.3
  - packaging=23.1
  - pandas=2.0.1
  - pandoc=2.19.2
  - pandocfilters=1.5.0
  - parquet-cpp=1.5.1
  - parso=0.8.3
  - partd=1.4.0
  - pcre2=10.40
  - pickleshare=0.7.5
  - pillow=9.5.0
  - pip=23.1.2
  - pixman=0.40.0
  - pkgutil-resolve-name=1.3.10
  - platformdirs=3.5.1
  - plotly=5.14.1
  - pluggy=1.0.0
  - pooch=1.7.0
  - poppler=23.05.0
  - poppler-data=0.4.12
  - postgresql=15.3
  - proj=9.2.0
  - prometheus_client=0.16.0
  - prompt-toolkit=3.0.38
  - prompt_toolkit=3.0.38
  - psutil=5.9.5
  - pthread-stubs=0.4
  - pure_eval=0.2.2
  - pyarrow=12.0.0
  - pycosat=0.6.4
  - pycparser=2.21
  - pygments=2.15.1
  - pyopenssl=23.1.1
  - pyparsing=3.0.9
  - pyproj=3.5.0
  - pyrsistent=0.19.3
  - pysocks=1.7.1
  - python=3.10.11
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.3
  - python-json-logger=2.0.7
  - python-tzdata=2023.3
  - python_abi=3.10
  - pytz=2023.3
  - pywin32=304
  - pyyaml=6.0
  - pyzmq=25.0.2
  - re2=2023.02.02
  - requests=2.29.0
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rtree=1.0.1
  - ruamel.yaml=0.17.26
  - ruamel.yaml.clib=0.2.7
  - scikit-learn=1.2.2
  - scipy=1.10.1
  - send2trash=1.8.2
  - setuptools=67.7.2
  - shapely=2.0.1
  - six=1.16.0
  - snappy=1.1.10
  - sniffio=1.3.0
  - sortedcontainers=2.4.0
  - soupsieve=2.3.2.post1
  - sqlite=3.42.0
  - stack_data=0.6.2
  - tbb=2021.9.0
  - tblib=1.7.0
  - tenacity=8.2.2
  - terminado=0.15.0
  - threadpoolctl=3.1.0
  - tiledb=2.13.2
  - tinycss2=1.2.1
  - tk=8.6.12
  - toolz=0.12.0
  - tornado=6.3.2
  - tqdm=4.65.0
  - traitlets=5.9.0
  - typing-extensions=4.5.0
  - typing_extensions=4.5.0
  - tzdata=2023c
  - unicodedata2=15.0.0
  - urllib3=1.26.15
  - wcwidth=0.2.6
  - webencodings=0.5.1
  - websocket-client=1.5.1
  - wheel=0.40.0
  - win_inet_pton=1.1.0
  - xerces-c=3.2.4
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xyzservices=2023.5.0
  - xz=5.2.6
  - yaml=0.2.5
  - zeromq=4.3.4
  - zict=3.0.0
  - zipp=3.15.0
  - zlib=1.2.13
  - zstandard=0.19.0
  - zstd=1.5.2
